---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template will create the resources need in Ohio Region

Resources:
  #CMK Key for S3 encryption in Ohio region
  MyKeyOhio: 
    Type: AWS::KMS:KEY
    Properties: 
    Description: This is a CMK key for encrypt my S3 bucket
    Enabled: True
    EnabledKeyRotation: True
    KeyPolicy: 
      Id: my_test_key
      Version: ‘2012-10-17’
      Statement:
      -	Sid: Enable IAM User Permissions
        Effect: Allow
        Principal:
          AWS:
          - Fn::Join:
            - “:”
          – - ‘arn:aws:iam:’
          - Ref: AWS::AccountId
          - Root
        Action: kms:*
        Resource: “*”
    Tags: 
    -	Key: Name
      Value: Test_Key
  #S3 Bucket for replication
  MyBucketTestOhio:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-test-bucket-ohio-replication
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID:
                !Ref: MyKeyOhio
              SSEAlgorithm: aws:kms
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: False
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: Name
          Value: my-test-bucket-ohio-replication

  #S3 Bucket Policy for my-test-bucket-ohio-replication
  MyBucketTestOhioBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucketTestOhio
      PolicyDocument:
        Statement:
        - Sid: AllowSSLRequestsOnly
          Action: s3:*
          Effect: Deny
          Resource:
            - !Ref MyBucketTestOhio
            - !Ref MyBucketTestOhio/*
          Condition:
            Bool:
              aws:SecureTransport: 'false'
          Principal: "*"
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::accountID:root
          Action: "*"
          Resource: 
            - MyBucketTestOhio
